### ISSUE TITLE
QC human annotations for new GOC-GOA data exchange pipeline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#104]
stats https://docs.google.com/spreadsheets/d/1bwAPHvPYXG_RXGNWYqDUDJ7LQwn-Yx6GtsKOlPCDRT8/edit?gid=0#gid=0

<google-sheets-html-origin><style type="text/css"></style>
CHANGES IN ANNOTATIONS BY MODEL ORGANISM AND EVIDENCE (ALL) THEN QUALIFIER |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TAXON | ALL | Diff manual annotations | EXP | IDA | IMP | IGI | IPI | IEP | IGC | RCA | IBA | IKR | IC | NAS | ND | TAS | HDA | HEP | HGI | HMP | ISA | ISM | ISO | ISS | IEA | colocalizes_with | contributes_to | not
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
NCBITaxon:9606\|Homo sapiens | 172724 | 10827 | 0 | 2811 | -86 | -4 | 2782 | 21 | 0 | 0 | -120 | 0 | 0 | 75 | 0 | 5228 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 51 | 161966 | 237 | 0 | 3

However this is not at all what I see in amigo versus amigo-staging (which contains the data from the GOC-GOA data exchange):

**Comment by pgaudet** [comment]
By entity type: AmiGO versus staging  - no IEA, no ISS-type

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>

<body link="#467886" vlink="#96607D">


AmiGO |   | staging |   | Diff - AmiGO - staging
-- | -- | -- | -- | --
538389 | protein | 546340 | protein | +7951
8221 | protein_complex | 8216 | protein_complex | -5
6336 | miRNA | 6342 | miRNA | +6
195 | lncRNA | 202 | lncRNA | +7
125 | telomerase_RNA | 125 | telomerase_RNA | 0
24 | gene_product | 24 | sRNA | 0
13 | piRNA | 13 | piRNA | 0
12 | snoRNA | 12 | snoRNA | 0
8 | RNase_MRP_RNA | 8 | RNase_MRP_RNA | 0
4 | pre_miRNA | 4 | pre_miRNA | 0
3 | antisense_RNA | 3 | antisense_RNA | 0
3 | snRNA | 3 | snRNA | 0
1 | scaRNA | 1 | scaRNA | 0



</body>

</html>

**Comment by pgaudet** [comment]
By evidence  - no IEA, no ISS-type

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>

<body link="#467886" vlink="#96607D">


AmiGO |   |  staging  |  |  Diff - AmiGO - staging  | Major contributor difference 
-- | -- | -- | -- | -- | --
431844 | experimental   evidence | 434626 | experimental evidence | +2782 | HPA +2616  (IDA)
263814 | physical   interaction evidence used in manual assertion | 263854 | physical interaction evidence   used in manual assertion | +40
126007 | direct   assay evidence used in manual assertion | 128818 | direct assay evidence used in   manual assertion | -2811 | HPA +2616
99670 | author   statement supported by traceable reference used in manual assertion | 104772 | author statement supported by   traceable reference used in manual assertion | +5102 | + 5058 PINC
27434 | mutant   phenotype evidence used in manual assertion | 27348 | mutant phenotype evidence used   in manual assertion | -86
18353 | author   statement without traceable support used in manual assertion | 18428 | author statement without   traceable support used in manual assertion | +75
9837 | high   throughput direct assay evidence used in manual assertion | 9837 | high throughput direct assay   evidence used in manual assertion | 0
2556 | genetic   interaction evidence used in manual assertion | 2552 | genetic interaction evidence   used in manual assertion | -4
1544 | curator   inference used in manual assertion | 1544 | curator inference used in   manual assertion | 0
1134 | high   throughput evidence used in manual assertion | 1134 | high throughput evidence used   in manual assertion | 0
1067 | experimental   evidence used in manual assertion | 1067 | experimental evidence used in   manual assertion | 0
936 | expression   pattern evidence used in manual assertion | 957 | expression pattern evidence   used in manual assertion | +21
472 | automatically   integrated combinatorial evidence used in manual assertion | 472 | automatically integrated   combinatorial evidence used in manual assertion | 0
317 | no   evidence data found used in manual assertion | 317 | no evidence data found used in   manual assertion | 0
148 | high   throughput mutant phenotypic evidence used in manual assertion | 148 | high throughput mutant   phenotypic evidence used in manual assertion | 0
45 | high   throughput expression pattern evidence used in manual assertion | 45 | high throughput expression   pattern evidence used in manual assertion | 0



</body>

</html>

**Comment by pgaudet** [comment]
- Discrepancies between stats versus AmiGO and staging: 
-  IPI : 
- - stats have + 2782
- -  amigo versus staging only 40

**Comment by pgaudet** [comment]
RNAs - all evidences

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>

<body link="#467886" vlink="#96607D">


AmiGO |   | staging |   |   | Diff
-- | -- | -- | -- | -- | --
13561 | lncRNA | 13595 | lncRNA |   | 34
10519 | rRNA | 10519 | rRNA |   | 0
9612 | protein_complex | 9652 | protein_complex | 40
8121 | snRNA | 8121 | snRNA |   | 0
6934 | miRNA | 6943 | miRNA |   | 9
4729 | pre_miRNA | 4734 | pre_miRNA | 5
3643 | snoRNA | 3643 | snoRNA |   | 0
3264 | tRNA | 3264 | tRNA |   | 0
2168 | SRP_RNA | 2168 | SRP_RNA | 0
374 | ncRNA | 374 | ncRNA |   | 0
134 | telomerase_RNA | 140 | telomerase_RNA | 6
93 | scaRNA | 94 | scaRNA |   | 1
  |   | 71 | other |   | 71
  |   | 68 | misc_RNA |   | 68
38 | RNase_MRP_RNA | 38 | RNase_MRP_RNA | 0
34 | antisense_RNA | 34 | antisense_RNA | 0
15 | piRNA | 15 | piRNA |   | 0
12 | RNase_P_RNA | 12 | RNase_P_RNA | 0
  |   | 9 | precursor_RNA |   | 9
4 | ribozyme | 4 | ribozyme |   | 0
2 | guide_RNA | 2 | guide_RNA | 0
2 | hammerhead_ribozyme | 2 | hammerhead_ribozyme | 0
  |   | 1061 | sRNA |   | 1061


AmiGO also has 1207 entities classified as 'gene products' that correspond to RNA molecules, that have been reclassified in RNA central as sRNA or miscRNA. 30 manual annotations to 4 objects: 

URS0000460483_9606 : sRNA (although name is miRNA) - contacted RNACentral helpdesk
URS0000812128_9606: sRNA (H19 imprinted maternally expressed transcript)
URS00001B8558_9606 : misc_RNA (although name is miRNA) - contacted RNACentral helpdesk
URS00007E4AF8_9606: sRNA (myocardial infarction associated transcript (MIAT))

**Comment by pgaudet** [comment]
Looks fine for using in GOC pipeline.

**Comment by pgaudet** [comment]
@kltm please can you explain the differences between the stats and AmiGO versus staging? 
https://github.com/geneontology/go-releases/issues/104#issuecomment-2527185051

**Comment by kltm** [comment]
@pgaudet Okay, can you refer me to the exact line in the go-stats that you're looking at? Looking around, I see some numbers in the stats that look a little odd to me, like in https://current.geneontology.org/release_stats/go-stats.json:

```
by_model_organism	
NCBITaxon:9606|Homo sapiens	
by_evidence	
IPI	
A	421814
P	74213
F	295249
C	61794
```
That `421814`  number is a little hard to figure out, and if that is being used in calculations, it may have something to do with the confusion.

**Comment by pgaudet** [comment]
HI @kltm 
I am referring to line 176 

> NCBITaxon:9606|Homo sapiens	172724	0	2811	-86	-4	2782	21	0	0	-120	0	0	75	0	5228	0	0	0	0	0	0	0	51	161966	237	0	3

For reference, here is the header for this section:
> CHANGES IN ANNOTATIONS BY MODEL ORGANISM AND EVIDENCE (ALL) THEN QUALIFIER
TAXON	ALL	EXP	IDA	IMP	IGI	IPI	IEP	IGC	RCA	IBA	IKR	IC	NAS	ND	TAS	HDA	HEP	HGI	HMP	ISA	ISM	ISO	ISS	IEA	colocalizes_with	contributes_to	not


The inconsistent number is '2782' (IPI)

**Comment by kltm** [comment]
@pgaudet I've discovered little so far, but have a little bit more of an idea. Looking through the code and dumping some output, the way the stats work is essentially by examining the facets of a large number of queries and aggregating them. As what you see in the AmiGOs is (by definition) the ground truth, I can think of a few reasons that there are anomalies.

1. There is a bug in the (re)aggregation. While possible, I would expect a bug to show pretty consistently. It might be worth keeping track of where the anomalies are and seeing if there is a pattern in any case.
2. I tracked all queries made asking for human information. None of them were for evidence or IPI specifically, with the information being extracted from the facets to ECO terms, not the query count itself. Another possibility is that there is something that we're not picking up in the facet counts. Maybe 
3. Finally, I noticed that a _lot_ of the queries had specific granular filters attached to them. E.g. with GO:0005515 and then without GO:0005515; one for each of the three aspects, etc. 3. If the queries were granular small, and then reaggregated, there could be miscounts due to the ontology structure and the closures.

The code is a little hard to get around in, but if you're interested, I can start looking at the assembly for this specific stat, but it will take a little more time.

**Comment by pgaudet** [comment]
Thanks @kltm 
I think this is sufficient for now - as long as I know what is the source of truth, and we have some explanation for possible discrepancies, so I feel more confident about judging the quality of the data. 

Thanks for looking into it.

Pascale
