### ISSUE TITLE
Changing Ecoli source data: from EcoWiki to EcoCyc

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#20]
Changing Ecoli source data: 

- [x] DONE Debbie confirmation 
Change datasets.yaml 
- [x] Email: biocyc-support@ai.sri.com for the contact address for EcoCyc.
- [x] Grant number is GM077678. 
- [x] File source: https://github.com/geneontology/go-site/blob/master/metadata/datasets/ecocyc.yaml

**Comment by pgaudet** [comment]
Background: 
- Issue data from EcoWiki source (https://ecoliwiki.org/gaf/gene_association.ecocyc.gz (s) out of date: most recent is from 2021-09-28 UniProt runs IEAs (ie, InterPro, RHEA, EC, KWs) at each release (about 1-2 months) - 
- Proposal is for GOA to directly load data from EcoCyc 
- GOA already loads CollecTF (although, most recent file from 2017)

**Comment by pgaudet** [comment]
Remaining issue: do we need further fixes to the yaml file? 
https://github.com/geneontology/go-site/blob/master/metadata/datasets/ecocyc.yaml

**Comment by pgaudet** [comment]
Changed yaml file for file source : https://github.com/geneontology/go-site/pull/1981
(Now GOA) 

@kltm

**Comment by kltm** [comment]
@pgaudet The ticket we should be referring to is https://github.com/geneontology/go-site/issues/1961, right?
