### ISSUE TITLE
Change sources: Human, chicken, dog, pig, cow files

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#62]
See https://github.com/geneontology/go-site/issues/2214

These combined files for Human, chichen, dog, pig, cow files, containing all Swiss-Prot isoforms, (not the TrEMBL isoforms), complexes, and RNAs.

**Comment by kltm** [comment]
@pgaudet As this is a metadata change that will affect the files we output, is this part of the pipeline project or something else? I'm assuming that this is to 1) somewhat change the data input for clarity and 2) make "debugging" easier at your end.

**Comment by pgaudet** [comment]
We can change projects if that makes sense, and I can add a note in the GO release QC project.

**Comment by pgaudet** [comment]
Done in 2024-05-12 snapshot, see https://github.com/geneontology/go-releases/issues/87
