### ISSUE TITLE
SynGO new data load

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#66]
Email by Frank Koopmans, Dec 1, 2023

> Hi,
It's been a while since the last SynGO update but today we've finished our work on update v1.2; I've uploaded the dataset to GitHub as per usual. (last time we sent data your way was to address some minor issues/fixes that Pascale requested in July 2022)
This is just a friendly headsup from my end, I'm not sure whether this has to be followed up on GO's end or whether data integrations proceed smoothly. If you encounter any issues with the new dataset, please let me know!

>data uploaded here: https://github.com/geneontology/syngo2lego_data_conversion 
travis link: https://travis-ci.org/github/geneontology/syngo2lego_data_conversion 

>The travis thing doesn't seem to work anymore (for me), so I cannot see whether parsing of the JSON went well. The error message I see on the travis link; "We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution."

> Best,
Frank

**Comment by pgaudet** [comment]
Emailed @dustine32 and @kltm to follow up on this

**Comment by kltm** [comment]
@dustine32 This completed at your end in the last noctua update, right?

**Comment by kltm** [comment]
@dustine32 Ah, here: https://github.com/geneontology/noctua/issues/866 https://github.com/geneontology/noctua-models/pull/272

**Comment by dustine32** [comment]
@kltm Yep, the models went into Noctua during the 2024-03-14 outage. I'm also supposed to notify Frank once these annotations are in a new GO release.

**Comment by pgaudet** [comment]
From: Dustin Ebert <[debert@usc.edu](mailto:debert@usc.edu)>
Sent: Monday, April 15, 2024 10:57 PM
To: Koopmans, F.T.W. (Frank) <[frank.koopmans@vu.nl](mailto:frank.koopmans@vu.nl)>; Pascale Gaudet <[Pascale.Gaudet@sib.swiss](mailto:Pascale.Gaudet@sib.swiss)>
Subject: Re: SynGO release 1.2 uploaded to syngo2lego_data_conversion GitHub repo
 
Hi Frank,

Just letting you know that the latest SynGO data, after [converting](https://github.com/geneontology/noctua-models/pull/273) to GO-CAM, has been integrated into GO release [2024-03-28](https://release.geneontology.org/2024-03-28/index.html).

Thanks!

-Dustin

----

This is great, thanks for the heads-up !

Best,
Frank

**Comment by pgaudet** [comment]
SynGO | 1458 / 11205 | 13.01%  in 2024-03-28 snapshot
