### ISSUE TITLE
2024-03-28 snapshot - Tree Grafter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-releases#77]
Hi @kltm 

This version of snapshot contains TreeGrafter data for 3 species: 
- Schizosaccharomyces pombe 
- Schizosaccharomyces japonicus
- Xenopus laveis 

However, given that these taxa are in the 'authoritative sources' metadata files, I would expect the IEAs not to be loaded in the first place. 

Is this filter not working in this case?

**Comment by dustine32** [comment]
> 'authoritative sources' metadata files

@pgaudet This refers specifically to the [go-reference-species.yaml](https://github.com/geneontology/go-site/blob/master/metadata/go-reference-species.yaml) file in `go-site`, right?

- This file is based on the PANTHER 15.0 taxa list whereas the PAINT IBAs are now on PANTHER 17.0 so, I'll have to update this file to the 17.0 list. https://github.com/geneontology/go-site/pull/2289
- I don't see Schizosaccharomyces japonicus (`NCBITaxon:402676`) or Xenopus laevis (`NCBITaxon:8355`) in `go-reference-species.yaml`. _S. japonicus_ will be added when I update the `go-reference-species.yaml` to 17.0 but _X. laevis_ won't be added until PANTHER 19.0 (soon to come a month or two). So, I believe it is correct for the _X. laevis_ TreeGrafter IEAs to be present (not filtered out) in this release.
- For Schizosaccharomyces pombe, we still have the species (`NCBITaxon:4896`) vs. strain (`NCBITaxon:284812`) taxon issue. and the new [GORULE:0000064](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000064.md) matches on `taxon_id` (currently `NCBITaxon:284812` in [go-reference-species.yaml](https://github.com/geneontology/go-site/blob/bf88bda9b0535b3d43ffad9ff6abd6e8c923dbae/metadata/go-reference-species.yaml#L193)). The PAINT IBAs for _S. pombe_ use the strain taxon for now (changing this to the species taxon soon - [ticket here](https://github.com/pantherdb/fullgo_paint_update/issues/60)) so I would assume that all TreeGrafter IEAs using strain taxon `284812` should currently be getting filtered out of the release. But it sounds like TreeGrafter IEAs to both taxa `4896` and `284812` are observed in the release, correct @pgaudet? If yes, we'll need to debug why @mugitty.

**Comment by pgaudet** [comment]
Hi @dustine32 
No, I was referring to the data in the metadata.yaml file for each [contributing group](https://github.com/geneontology/go-site/tree/master/metadata/datasets): here's the [pombe](https://github.com/geneontology/go-site/blob/master/metadata/datasets/pombase.yaml), and the [xenopus](https://github.com/geneontology/go-site/blob/master/metadata/datasets/xenbase.yaml) file. I thought the taxa in these files were excluded from the goa-uniprot-all load. 

However now I see that this data is in the [pombase upstream file](https://www.pombase.org/data/annotations/Gene_ontology/gene_association.pombase.gz), and likewise for XenBase, so this is then the upstream that decided to load them. 

So, this is not a GO Central issue. Sorry about the false alarm! 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Oh, ok! So this does not have anything to do with the new GORULE:0000064?

**Comment by pgaudet** [comment]
> So this does not have anything to do with the new GORULE:0000064?

No: GORULE:0000064 should exclude any annotations from the NCBITaxon:284812 reference species, which it does. 

However the file for pombe that we produce (http://release.geneontology.org/2024-03-28/annotations/pombase.gaf.gz) does have TreeGrafter annotations, while the source files doesn't (http://release.geneontology.org/2024-03-28/products/upstream_and_raw_data/paint_pombase-src.gaf.gz). I thought that the GO parser should exclude TreeGrafter annotations, since Pombase is listed as the authority on both NCBITaxon:284812 and NCBITaxon:4896 (see http://release.geneontology.org/2024-03-28/metadata/datasets/pombase.yaml), so all IEA annotations should be coming from the the pombase source file, ie http://release.geneontology.org/2024-03-28/products/upstream_and_raw_data/paint_pombase-src.gaf.gz

I dont see any TreeGrafter annotations in this file. How did we get them?

**Comment by dustine32** [comment]
> so all IEA annotations should be coming from the the pombase source file, ie http://release.geneontology.org/2024-03-28/products/upstream_and_raw_data/paint_pombase-src.gaf.gz

@pgaudet Do you mean `pombase-src.gaf.gz`, not `paint_pombase-src.gaf.gz`, is the pombase source file? I checked the file coming from upstream PomBase (https://release.geneontology.org/2024-03-28/products/upstream_and_raw_data/pombase-src.gaf.gz) and did indeed find it contained those TreeGrafter IEA annotations:
```
$ grep GO_REF:0000118 pombase-src.gaf | wc -l
    1461
```
Though, once I merge https://github.com/geneontology/go-site/pull/2289 these annotations should be getting filtered out of the final GO product `pombase.gaf` because the taxon IDs (`NCBITaxon:4896`) will match [go-reference-species.yaml](https://github.com/geneontology/go-site/blob/f8a6c54053eea7554b175dbe18185f7d1855966f/metadata/go-reference-species.yaml#L253). Note: the `GORULE:0000064` code only looks at taxa listed in [go-reference-species.yaml](https://github.com/geneontology/go-site/blob/master/metadata/go-reference-species.yaml) rather than the taxa in metadata group datasets YAML files.

**Comment by pgaudet** [comment]
Thanks @dustine32 !!! I think I was tired yesterday - this is what I had seen last week, and yesterday I was evidently looking in the wrong file... 


> Though, once I merge https://github.com/geneontology/go-site/pull/2289 these annotations should be getting filtered out of the final GO product pombase.gaf because the taxon IDs (NCBITaxon:4896) will match [go-reference-species.yaml](https://github.com/geneontology/go-site/blob/f8a6c54053eea7554b175dbe18185f7d1855966f/metadata/go-reference-species.yaml#L253). 

Perfect!

**Comment by dustine32** [comment]
@pgaudet Great! @kltm just merged https://github.com/geneontology/go-site/pull/2289 so the pipeline should now be properly filtering out TreeGrafter IEAs for S. pombe and S. japonicus. We'll test this in the next `snapshot`.
